name: Release

on: workflow_dispatch

permissions:
  contents: write

jobs:
  release:

    runs-on: ubuntu-latest

    steps:
      - uses: step-security/harden-runner@c8454efe5d0bdefd25384362fe217428ca277d57 # 2.2.0
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443
            github.com:443
            registry.npmjs.org:443
            registry.yarnpkg.com:443
            uploads.github.com:443

      - name: Checkout
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # 3.3.0
        with:
          persist-credentials: false
          token: ${{ secrets.SEMANTIC_RELEASE_PAT }}

      - name: Install Node
        uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # 3.6.0
        with:
          node-version: 16

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build plugin
        run: yarn build-prod

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@8f6ceb9d5aae5578b1dcda6af00008235204e7fa # 3.2
        id: semantic
        with:
          semantic_version: 19.0.2
          branch: main
          extra_plugins: |
            @semantic-release/changelog@6.0.2
            @semantic-release/exec@6.0.3
            @amille/semantic-release-plugins@3.3.12
            @semantic-release/git@10.0.1
            conventional-changelog-conventionalcommits@5.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.SEMANTIC_RELEASE_PAT }}
          NPM_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

      - name: Outputs
        run: |
          cat <<EOO >> $GITHUB_STEP_SUMMARY
            ---

            ### Semantic release output

            <table>
              <tr><th>published</th><td>${{ steps.semantic.outputs.new_release_published }}</td></tr>
              <tr><th>last release</th><td>${{ steps.semantic.outputs.last_release_version }}</td></tr>
              <tr><th>next release</th><td>${{ steps.semantic.outputs.new_release_version }}</td></tr>
            </table>

            ---

            #### Release-Notes

            ${{ steps.semantic.outputs.new_release_notes }}

          ---
          EOO
