name: Test-Release

on:
  push:
    branches-ignore: [dependabot/**]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    name: test release

    runs-on: ubuntu-latest

    steps:
      - uses: step-security/harden-runner@18bf8ad2ca49c14cbb28b91346d626ccfb00c518 # 2.1.0
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            github.com:443
            registry.npmjs.org:443

      - name: Get branch name
        uses: tj-actions/branch-names@eee8675bd61ec38bcfbfedd504d8473292ba649e # 6.4
        id: branch-name

      - name: Checkout
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # 3.3.0

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@8f6ceb9d5aae5578b1dcda6af00008235204e7fa # 3.2
        id: semantic
        with:
          dry_run: true
          semantic_version: 19.0.2
          branch: ${{ steps.branch-name.outputs.current_branch }}
          extra_plugins: |
            @semantic-release/changelog@6.0.2
            @semantic-release/exec@6.0.3
            @amille/semantic-release-plugins@3.3.12
            @semantic-release/git@10.0.1
            conventional-changelog-conventionalcommits@5.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

      - name: Test Outputs
        run: |
          cat <<EOO >> $GITHUB_STEP_SUMMARY
            ---

            ### Semantic release output (DRY-RUN)

            <table>
              <tr><th>published</th><td>${{ steps.semantic.outputs.new_release_published }}</td></tr>
              <tr><th>last release</th><td>${{ steps.semantic.outputs.last_release_version }}</td></tr>
              <tr><th>next release</th><td>${{ steps.semantic.outputs.new_release_version }}</td></tr>
            </table>

            ---

            #### Release-Notes

            ${{ steps.semantic.outputs.new_release_notes }}

          ---
          EOO
